### ISSUE TITLE
Differentiated access policies

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/synspy#24]
Divide the current equivalence class of trusted users into more fine-grained permissions:

- [x] Enable delete controls but only for a curator group
- [x] Limit student workers to only updating their assigned tasks as required for launcher/viewer workflow

@BDemps are there any other differentiated access control policies you think would matter in the short term?  Is there a need for any read-only groups or even more limited ability to read some catalog info and not others?

**Comment by karlcz** [comment]
This is something we can worry about later this summer after the ERMrest fine-grained ACLs support lands.

**Comment by BDemps** [comment]
I think as long as the curators are you, me, and Zhuowei this should be
fine. Pretty much everyone else should be read only. Do you think this
makes sense?

On Jun 2, 2017 2:39 PM, "Karl Czajkowski" <notifications@github.com> wrote:

Divide the current equivalence class of trusted users into more
fine-grained permissions:

   - Enable delete controls but only for a curator group
   - Limit student workers to only updating their assigned tasks as
   required for launcher/viewer workflow

@BDemps
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_bdemps&d=DwMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=Lssj6JKak_DaRnExGYcKnQ&m=L2sz2KKOmUIoaDiMKzBKjzjBjvmSeahWWyhcimzyWpg&s=b-A-vA0dC2JVNDxkb85Y8v8PqXigRJCuK2CwcpB800k&e=>
are there any other differentiated access control policies you think would
matter in the short term? Is there a need for any read-only groups or even
more limited ability to read some catalog info and not others?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_informatics-2Disi-2Dedu_synspy_issues_24&d=DwMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=Lssj6JKak_DaRnExGYcKnQ&m=L2sz2KKOmUIoaDiMKzBKjzjBjvmSeahWWyhcimzyWpg&s=fZfz39sDbBZcUyAqOAPi_24KOdEJ6jrgPWdF00Vo_OY&e=>,
or mute the thread
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AbQSt7006ANrPWj0PchFtbFc0ykP-5FiG2ks5sAIEggaJpZM4Nu0rE&d=DwMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=Lssj6JKak_DaRnExGYcKnQ&m=L2sz2KKOmUIoaDiMKzBKjzjBjvmSeahWWyhcimzyWpg&s=CSPoTGFTbwwGpJnhOiJC_IHqwTc3-ZOyf43ZHRL2kKg&e=>
.

**Comment by karlcz** [comment]
This policy is in pilot evaluation now

**Comment by karlcz** [comment]
On Jul 19, BDemps modulated:
> So just you, Zhuowei and I have permission to delete? I'm gonna get an
> undergrad to sign in today and see if I can delete a dummy thing.
> 

Right, whoever is in the curator group has full reign.

Everyone else should be read-only except for limited ability to update
existing Image Region records for which they are the Classifier.

Given this upgrade to policies, server, and client tools, please
verify that the student can use the launcher and that new results are
actually captured properly!  We don't want them doing too much work
and finding out their efforts are discarded due to configuration
problems...


karl

**Comment by BDemps** [comment]
Captured properly meaning that segments that are selected as truth are
actually retained when you exit?

**Comment by karlcz** [comment]
Yes, verify the whole cycle works and that new work isn't lost.

**Comment by karlcz** [comment]
Bill confirmed out of band that launcher task results are saved properly for the less privileged user role.
