### ISSUE TITLE
Windows version saving request

### ISSUE THREAD

**Issue by BDemps** [informatics-isi-edu/synspy#29]
Currently, the files that are saved in the Windows version are automatically dumped to the C: drive. Would it be possible for the user to choose (maybe when starting the launcher for the first time) where they would prefer to store the images, in case the user's C: drive is mostly full?

**Comment by karlcz** [comment]
I think that you can modify the `cache_dir` location in the `.deriva/synapse/synspy-launcher/config.json` configuration file.  This by default is configured as a folder under your home directory (that's what the `~` represents).  Try changing it to a full path so it might look something like:

    {
       "cache_dir": "D:\\your\folder",
       "server": ...
    }

**Comment by karlcz** [comment]
whoops I forgot that backslashes will be awkward with this JSON formatted configuration... you might try forward slashes or else doubled up backslashes:

    "D://your/folder"

    "D:\\\\your\\folder"

because `\\` represents an escaped `\` in the JSON format of the configuration file...

**Comment by karlcz** [comment]
heh I had to update my previous comments again... I don't really speak Windows and forgot how their paths looked

**Comment by karlcz** [comment]
I think @mikedarcy is also adding GUI support to edit this setting from within the app.

**Comment by mikedarcy** [comment]
I've added a directory browser button in the options page of the GUI.  You can use this to change the download cache dir.  The change is persistent so you should only need to do it one time in order to change the path. Note that you must be logged in before the options button becomes enabled.

Added to release: https://github.com/informatics-isi-edu/synspy/releases/tag/v20170713.7
