### ISSUE TITLE
Nuclei segmentation in 2D viewer seems wrong

### ISSUE THREAD

**Issue by BDemps** [informatics-isi-edu/synspy#30]
The nuclei viewer seems to actually be segmenting synapses instead of nuclei, or it is at least behaving differently to what usually occurs in the linux room. As you can see in this image of a single optical section (with thresholds basically removed), the nuclei are more or less excluded and smaller dots are considered to be segments. This occurs on both the mac and windows versions.

![image](https://user-images.githubusercontent.com/28578487/28698186-7106a0d6-72f6-11e7-9983-2d2565a4cddd.png)

**Comment by karlcz** [comment]
Please give a specific region ID where this is happening.

**Comment by karlcz** [comment]
I think this issue is actually a bug in the server-side processing to produce the NPZ file used by the 2d viewer.  It was running in synaptic mode even when it was supposed to be in nucleic mode.  This would affect all 2d viewers regardless of client platform.  Only the 3D viewer would work differently, since it applies its own image processing instead of using the prepared NPZ file.

**Comment by karlcz** [comment]
This bug in synspy_worker was fixed in master.
