### ISSUE TITLE
Cannot define multiple image pairs with same image

### ISSUE THREAD

**Issue by BDemps** [informatics-isi-edu/synspy#43]
This is the error:
Error 409 Conflict The request conflicts with the state of the server. Input data violates model. ERROR: duplicate key value violates unique constraint "Image Pair Study_Image 1_key" DETAIL: Key ("Image 1")=(ImgZfDsy20170907A3) already exists.

And this is what I was trying to do:
I tried creating a new image pair study from ZfDsy20170907A. When I clicked "submit" that came up. Here's the screenshot
![image](https://user-images.githubusercontent.com/28578487/30769286-ef13f14e-9fca-11e7-90a0-fe10c6d4ae94.png)

**Comment by karlcz** [comment]
The catalog model only allows one image pair study per timestep 1 image. This is intentional since our goal is to identify the single canonical pair of before/after images we will analyze.

In this case, Std6563 already is defined with ImgZfDsy20170907A3 as the first image.  I found this by looking at the listing of image pair studies and [searching for that first image ID that was reported in your error message](https://synapse.isrd.isi.edu/chaise/recordset/#1/Zebrafish:Image%20Pair%20Study/*::search::ZfDsy20170907A3@sort\(RID::desc::\))

**Comment by karlcz** [comment]
By the way, I understand the GUI experience isn't ideal here since it offers you an option that won't work, but this is a known limitation of the current Chaise app and probably won't be fixed right away...  there are several complicated bits with making this work in general, and we need to get those sorted out before we can make the GUI smarter about excluding "already chosen" values in workflows where that is a concern...

**Comment by BDemps** [comment]
Can you help me understand how I did this wrong? I agree that today I was
able to define things just fine. I just don't know how I made the error in
the first place!
